/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/terminals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List terminals */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TerminalSummary'][];
          };
        };
      };
    };
    put?: never;
    /** Create a terminal (first version) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateTerminal'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TerminalSummary'];
          };
        };
        422: components['responses']['ValidationFailed'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    /** Get latest (or ?version=N) document */
    get: {
      parameters: {
        query?: {
          version?: number;
        };
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TerminalVersionDetail'];
          };
        };
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    /** Delete a terminal and its versions */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        404: components['responses']['NotFound'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    /** List versions */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['VersionInfo'][];
          };
        };
      };
    };
    put?: never;
    /** Save a new version (append-only). Use restore_from to copy an older version. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SaveVersion'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['VersionInfo'];
          };
        };
        422: components['responses']['ValidationFailed'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import a terminal from JSON or a CSV bundle (all-or-nothing) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ImportJson'];
          'multipart/form-data': {
            name: string;
            /** @description nodes.csv, elements.csv, tanks.csv, products.csv, changeover.csv (see csv-import.md) */
            files: string[];
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TerminalSummary'];
          };
        };
        422: components['responses']['ValidationFailed'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/export': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    /** Export latest version */
    get: {
      parameters: {
        query?: {
          format?: 'json' | 'csv';
        };
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description JSON document or zip of CSV files */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/validate': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate a document (supplied or latest) without saving */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            document?: components['schemas']['terminal-document.schema'];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              issues: components['schemas']['ValidationIssue'][];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/graph': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    /** Return the validated directed graph for a terminal version */
    get: {
      parameters: {
        query?: {
          /** @description Defaults to latest */
          version?: number;
        };
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Terminal nodes, elements, and derived directed arcs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TerminalGraph'];
          };
        };
        404: components['responses']['NotFound'];
        /** @description Semantic validation errors prevent an accurate graph projection */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              code: string;
              message: string;
              issues: components['schemas']['ValidationIssue'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/routes': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Quickest feasible routes for one operation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RouteRequest'];
        };
      };
      responses: {
        /** @description Routes (possibly empty) with explanations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['RouteResponse'];
          };
        };
        404: components['responses']['NotFound'];
        422: components['responses']['ValidationFailed'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/routes/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm the final route chosen from the shortlist (FR-023) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            request: components['schemas']['RouteRequest'];
            route: components['schemas']['Route'];
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfirmedRoute'];
          };
        };
        404: components['responses']['NotFound'];
        422: components['responses']['ValidationFailed'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/routes/confirmed': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    /** List confirmed routes (outdated ones flagged) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfirmedRoute'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/availability': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
      };
      cookie?: never;
    };
    /** List availability windows */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          element_id?: string;
        };
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AvailabilityWindow'][];
          };
        };
      };
    };
    put?: never;
    /** Upsert availability windows (idempotent by element_id+source+external_ref). Unknown elements are reported, not fatal. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            windows: components['schemas']['AvailabilityWindowInput'][];
          };
        };
      };
      responses: {
        /** @description Result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              applied: number;
              rejected: {
                index: number;
                reason: string;
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/terminals/{terminalId}/availability/{windowId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        terminalId: components['parameters']['TerminalId'];
        windowId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a window */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          terminalId: components['parameters']['TerminalId'];
          windowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        404: components['responses']['NotFound'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      code: string;
      message: string;
    };
    TerminalSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      current_version: number;
      /** Format: date-time */
      updated_at: string;
    };
    CreateTerminal: {
      name: string;
      document: components['schemas']['terminal-document.schema'];
    };
    ImportJson: {
      name: string;
      document: components['schemas']['terminal-document.schema'];
    };
    /** @description Exactly one of document or restore_from is required. */
    SaveVersion: {
      document?: components['schemas']['terminal-document.schema'];
      restore_from?: number;
      note?: string;
    };
    VersionInfo: {
      version: number;
      /** Format: date-time */
      created_at: string;
      note?: string;
    };
    TerminalVersionDetail: {
      /** Format: uuid */
      id: string;
      name: string;
      version: number;
      document: components['schemas']['terminal-document.schema'];
    };
    TerminalGraph: {
      terminal_version: number;
      nodes: {
        [key: string]: unknown;
      }[];
      elements: {
        [key: string]: unknown;
      }[];
      arcs: {
        id: string;
        element_id: string;
        from: string;
        to: string;
        reversed: boolean;
        traversable: boolean;
        /** @enum {string|null} */
        restriction?: 'ONE_WAY_PUMP' | null;
      }[];
      issues: components['schemas']['ValidationIssue'][];
    };
    ValidationIssue: {
      /** @enum {string} */
      severity: 'ERROR' | 'WARNING';
      code: string;
      element_id?: string;
      node_id?: string;
      /** @description CSV row for import errors */
      row?: number;
      file?: string;
      message: string;
      fix_hint?: string;
    };
    AvailabilityWindowInput: {
      element_id: string;
      status: components['schemas']['AvailabilityStatus'];
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to?: string | null;
      reason?: string;
      /** @default manual */
      source: string;
      external_ref?: string;
    };
    AvailabilityWindow: components['schemas']['AvailabilityWindowInput'] & {
      /** Format: uuid */
      id: string;
    };
    /** @enum {string} */
    AvailabilityStatus: 'AVAILABLE' | 'MAINTENANCE' | 'FLUSHING' | 'CLEANING' | 'OUT_OF_SERVICE';
    RouteRequest: {
      /** @description Defaults to latest */
      version?: number;
      /** @enum {string} */
      direction: 'IN' | 'OUT' | 'TRANSFER';
      product_id: string;
      volume_m3: number;
      rate_m3h: number;
      /** Format: date-time */
      window_from: string;
      /**
       * Format: date-time
       * @description Defaults to window_from plus transfer time
       */
      window_to?: string;
      source_ids: string[];
      destination_ids: string[];
      /** @default 5 */
      max_routes: number;
    };
    RouteResponse: {
      terminal_version: number;
      engine_version: string;
      routes: components['schemas']['Route'][];
      exclusions: components['schemas']['Exclusion'][];
      no_route?: components['schemas']['NoRoute'];
    };
    Route: {
      rank: number;
      source_id: string;
      destination_id: string;
      steps: {
        element_id: string;
        from: string;
        to: string;
        reversed: boolean;
      }[];
      metrics: {
        fill_min: number;
        transfer_min: number;
        flush_min: number;
        flush_volume_m3: number;
        total_min: number;
        valves: number;
        common_headers: number;
        head_margin_m: number;
        max_velocity_ms: number;
      };
    };
    Exclusion: {
      element_id?: string;
      node_id?: string;
      /** @enum {string} */
      reason:
        | 'NOT_CERTIFIED'
        | 'VELOCITY'
        | 'RESIDUE'
        | 'ONE_WAY_PUMP'
        | 'UNAVAILABLE'
        | 'DEDICATED_OTHER_GROUP'
        | 'PUMP_HEAD'
        | 'ENDPOINT_STOCK'
        | 'ENDPOINT_SPACE'
        | 'ENDPOINT_PRODUCT'
        | 'ENDPOINT_DIRECTION';
      detail: string;
    };
    ConfirmedRoute: {
      /** Format: uuid */
      id: string;
      terminal_version: number;
      request: components['schemas']['RouteRequest'];
      route: components['schemas']['Route'];
      outdated: boolean;
      outdated_reason?: string;
      /** Format: date-time */
      created_at: string;
    };
    NoRoute: {
      message: string;
      blockers: components['schemas']['Exclusion'][];
    };
    Id: string;
    Product: {
      id: components['schemas']['Id'];
      name: string;
      group?: string;
      /** @default 0.018 */
      friction_factor: number;
      /** @default 3 */
      max_velocity: number;
      color?: string;
    };
    ChangeoverRule: {
      from_product: components['schemas']['Id'];
      to_product: components['schemas']['Id'];
      /** @default 0 */
      gap_min: number;
      /** @default 0 */
      flush_factor: number;
      /** @default false */
      manual_clean_required: boolean;
    };
    TankGroup: {
      id: components['schemas']['Id'];
      name: string;
      tank_ids?: components['schemas']['Id'][];
    };
    Node: {
      id: components['schemas']['Id'];
      /** @enum {unknown} */
      type:
        'TANK' | 'JETTY' | 'LOADING_POINT' | 'RAIL_PLATFORM' | 'RAIL_CAR' | 'MANIFOLD' | 'JUNCTION';
      name?: string;
      x?: number;
      y?: number;
      group_id?: components['schemas']['Id'];
      product_id?: components['schemas']['Id'] | null;
      stock_m3?: number;
      capacity_m3?: number;
      min_heel_m3?: number;
      /** @default true */
      allow_inbound: boolean;
      /** @default true */
      allow_outbound: boolean;
      /** @default false */
      allow_simultaneous: boolean;
      max_rate_m3h?: number;
      certified_products?: components['schemas']['Id'][];
      side_count?: number;
      cars_per_side?: number;
      platform_id?: components['schemas']['Id'];
    } & unknown;
    Element: {
      id: components['schemas']['Id'];
      /** @enum {unknown} */
      type: 'TANK_HEADER' | 'SEGMENT' | 'COMMON_HEADER' | 'LINE' | 'PUMP' | 'VALVE';
      from: components['schemas']['Id'];
      to: components['schemas']['Id'];
      length_m?: number;
      diameter_mm?: number;
      /** @default 0 */
      elevation_delta_m: number;
      /**
       * @default ABOVEGROUND
       * @enum {unknown}
       */
      installation: 'UNDERGROUND' | 'ABOVEGROUND';
      roughness_mm?: number;
      certified_products?: components['schemas']['Id'][];
      dedicated_group_id?: components['schemas']['Id'];
      dedicated_product_ids?: components['schemas']['Id'][];
      residue_product_id?: components['schemas']['Id'] | null;
      /** @default true */
      bidirectional: boolean;
      tank_id?: components['schemas']['Id'];
      head_m?: number;
      max_flow_m3h?: number;
      operate_min?: number;
      /** @enum {unknown} */
      state?: 'OPEN' | 'CLOSED';
    } & (unknown & unknown & unknown);
    /** TerminalDocument */
    'terminal-document.schema': {
      /** @constant */
      schema_version: '1.0';
      name: string;
      products: components['schemas']['Product'][];
      changeover?: components['schemas']['ChangeoverRule'][];
      tank_groups?: components['schemas']['TankGroup'][];
      nodes: components['schemas']['Node'][];
      elements: components['schemas']['Element'][];
      /** @description Optional editor-only data; ignored by engines */
      layout?: {
        [key: string]: unknown;
      };
      $defs: {
        Id: string;
        Product: {
          id: components['schemas']['Id'];
          name: string;
          group?: string;
          /** @default 0.018 */
          friction_factor: number;
          /** @default 3 */
          max_velocity: number;
          color?: string;
        };
        ChangeoverRule: {
          from_product: components['schemas']['Id'];
          to_product: components['schemas']['Id'];
          /** @default 0 */
          gap_min: number;
          /** @default 0 */
          flush_factor: number;
          /** @default false */
          manual_clean_required: boolean;
        };
        TankGroup: {
          id: components['schemas']['Id'];
          name: string;
          tank_ids?: components['schemas']['Id'][];
        };
        Node: {
          id: components['schemas']['Id'];
          /** @enum {unknown} */
          type:
            | 'TANK'
            | 'JETTY'
            | 'LOADING_POINT'
            | 'RAIL_PLATFORM'
            | 'RAIL_CAR'
            | 'MANIFOLD'
            | 'JUNCTION';
          name?: string;
          x?: number;
          y?: number;
          group_id?: components['schemas']['Id'];
          product_id?: components['schemas']['Id'] | null;
          stock_m3?: number;
          capacity_m3?: number;
          min_heel_m3?: number;
          /** @default true */
          allow_inbound: boolean;
          /** @default true */
          allow_outbound: boolean;
          /** @default false */
          allow_simultaneous: boolean;
          max_rate_m3h?: number;
          certified_products?: components['schemas']['Id'][];
          side_count?: number;
          cars_per_side?: number;
          platform_id?: components['schemas']['Id'];
        } & unknown;
        Element: {
          id: components['schemas']['Id'];
          /** @enum {unknown} */
          type: 'TANK_HEADER' | 'SEGMENT' | 'COMMON_HEADER' | 'LINE' | 'PUMP' | 'VALVE';
          from: components['schemas']['Id'];
          to: components['schemas']['Id'];
          length_m?: number;
          diameter_mm?: number;
          /** @default 0 */
          elevation_delta_m: number;
          /**
           * @default ABOVEGROUND
           * @enum {unknown}
           */
          installation: 'UNDERGROUND' | 'ABOVEGROUND';
          roughness_mm?: number;
          certified_products?: components['schemas']['Id'][];
          dedicated_group_id?: components['schemas']['Id'];
          dedicated_product_ids?: components['schemas']['Id'][];
          residue_product_id?: components['schemas']['Id'] | null;
          /** @default true */
          bidirectional: boolean;
          tank_id?: components['schemas']['Id'];
          head_m?: number;
          max_flow_m3h?: number;
          operate_min?: number;
          /** @enum {unknown} */
          state?: 'OPEN' | 'CLOSED';
        } & (unknown & unknown & unknown);
      };
    };
  };
  responses: {
    /** @description Not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Input rejected; nothing was saved */
    ValidationFailed: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          issues: components['schemas']['ValidationIssue'][];
        };
      };
    };
  };
  parameters: {
    TerminalId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
