/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Node = {
  [k: string]: unknown;
} & {
  id: Id;
  type: 'TANK' | 'JETTY' | 'LOADING_POINT' | 'RAIL_PLATFORM' | 'RAIL_CAR' | 'MANIFOLD' | 'JUNCTION';
  name?: string;
  x?: number;
  y?: number;
  group_id?: Id;
  product_id?: Id | null;
  stock_m3?: number;
  capacity_m3?: number;
  min_heel_m3?: number;
  allow_inbound?: boolean;
  allow_outbound?: boolean;
  allow_simultaneous?: boolean;
  max_rate_m3h?: number;
  certified_products?: Id[];
  side_count?: number;
  cars_per_side?: number;
  platform_id?: Id;
  [k: string]: unknown;
};
export type Element = {
  [k: string]: unknown;
} & {
  id: Id;
  type: 'TANK_HEADER' | 'SEGMENT' | 'COMMON_HEADER' | 'LINE' | 'PUMP' | 'VALVE';
  from: Id;
  to: Id;
  length_m?: number;
  diameter_mm?: number;
  elevation_delta_m?: number;
  installation?: 'UNDERGROUND' | 'ABOVEGROUND';
  roughness_mm?: number;
  certified_products?: Id[];
  dedicated_group_id?: Id;
  dedicated_product_ids?: Id[];
  residue_product_id?: Id | null;
  bidirectional?: boolean;
  tank_id?: Id;
  head_m?: number;
  max_flow_m3h?: number;
  performance_curve?: PerformanceCurve;
  npsh_required_m?: number;
  npsh_margin_m?: number;
  operate_min?: number;
  state?: 'OPEN' | 'CLOSED';
  [k: string]: unknown;
};
export type PerformanceCurve = {
  [k: string]: unknown;
} & {
  model: 'QUADRATIC' | 'TABULAR';
  min_flow_m3h: number;
  max_flow_m3h: number;
  shutoff_head_m?: number;
  quadratic_coefficient?: number;
  points?: PerformancePoint[];
  speed_ratio_min: number;
  speed_ratio_max: number;
};

export interface TerminalDocument {
  schema_version: '1.0' | '1.1';
  name: string;
  products: Product[];
  changeover?: ChangeoverRule[];
  tank_groups?: TankGroup[];
  pump_trains?: PumpTrain[];
  nodes: Node[];
  elements: Element[];
  /**
   * Optional editor-only data; ignored by engines
   */
  layout?: {
    [k: string]: unknown;
  };
}
export interface Product {
  id: Id;
  name: string;
  group?: string;
  friction_factor?: number;
  max_velocity?: number;
  color?: string;
}
export interface ChangeoverRule {
  from_product: Id;
  to_product: Id;
  gap_min?: number;
  flush_factor?: number;
  manual_clean_required?: boolean;
}
export interface TankGroup {
  id: Id;
  name: string;
  tank_ids?: Id[];
}
export interface PumpTrain {
  id: Id;
  arrangement: 'SERIES' | 'PARALLEL';
  member_pump_ids: Id[];
}
export interface PerformancePoint {
  flow_m3h: number;
  head_m: number;
}
