# generated by datamodel-codegen:
#   filename:  terminal-document.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z0-9_.-]{1,64}$')]


class Product(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    name: str
    group: str | None = None
    friction_factor: Annotated[float | None, Field(ge=0.005, le=0.1)] = 0.018
    max_velocity: Annotated[float | None, Field(gt=0.0)] = 3.0
    color: Annotated[str | None, Field(pattern='^#[0-9A-Fa-f]{6}$')] = None


class ChangeoverRule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_product: Id
    to_product: Id
    gap_min: Annotated[float | None, Field(ge=0.0)] = 0
    flush_factor: Annotated[float | None, Field(ge=0.0)] = 0
    manual_clean_required: bool | None = False


class TankGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    name: str
    tank_ids: list[Id] | None = None


class Type(Enum):
    TANK = 'TANK'
    JETTY = 'JETTY'
    LOADING_POINT = 'LOADING_POINT'
    RAIL_PLATFORM = 'RAIL_PLATFORM'
    RAIL_CAR = 'RAIL_CAR'
    MANIFOLD = 'MANIFOLD'
    JUNCTION = 'JUNCTION'


class Node(BaseModel):
    id: Id
    type: Type
    name: str | None = None
    x: float | None = None
    y: float | None = None
    group_id: Id | None = None
    product_id: Id | None = None
    stock_m3: Annotated[float | None, Field(ge=0.0)] = None
    capacity_m3: Annotated[float | None, Field(gt=0.0)] = None
    min_heel_m3: Annotated[float | None, Field(ge=0.0)] = None
    allow_inbound: bool | None = True
    allow_outbound: bool | None = True
    allow_simultaneous: bool | None = False
    max_rate_m3h: Annotated[float | None, Field(gt=0.0)] = None
    certified_products: list[Id] | None = None
    side_count: Annotated[int | None, Field(ge=1)] = None
    cars_per_side: Annotated[int | None, Field(ge=1)] = None
    platform_id: Id | None = None


class Type1(Enum):
    TANK_HEADER = 'TANK_HEADER'
    SEGMENT = 'SEGMENT'
    COMMON_HEADER = 'COMMON_HEADER'
    LINE = 'LINE'
    PUMP = 'PUMP'
    VALVE = 'VALVE'


class Installation(Enum):
    UNDERGROUND = 'UNDERGROUND'
    ABOVEGROUND = 'ABOVEGROUND'


class State(Enum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'


class Element(BaseModel):
    id: Id
    type: Type1
    from_: Annotated[Id, Field(alias='from')]
    to: Id
    length_m: Annotated[float | None, Field(ge=0.0)] = None
    diameter_mm: Annotated[float | None, Field(gt=0.0)] = None
    elevation_delta_m: float | None = 0
    installation: Installation | None = 'ABOVEGROUND'
    roughness_mm: Annotated[float | None, Field(ge=0.0)] = None
    certified_products: list[Id] | None = None
    dedicated_group_id: Id | None = None
    dedicated_product_ids: list[Id] | None = None
    residue_product_id: Id | None = None
    bidirectional: bool | None = True
    tank_id: Id | None = None
    head_m: Annotated[float | None, Field(ge=0.0)] = None
    max_flow_m3h: Annotated[float | None, Field(gt=0.0)] = None
    operate_min: Annotated[float | None, Field(ge=0.0)] = None
    state: State | None = None


class TerminalDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    name: Annotated[str, Field(max_length=120, min_length=1)]
    products: list[Product]
    changeover: list[ChangeoverRule] | None = None
    tank_groups: list[TankGroup] | None = None
    nodes: list[Node]
    elements: list[Element]
    layout: Annotated[
        dict[str, Any] | None,
        Field(description='Optional editor-only data; ignored by engines'),
    ] = None
